{{- range .Values.activeDirectory.gmsas }}
{{- $suffix := lower . -}}
---
apiVersion: windows.k8s.io/v1
kind: GMSACredentialSpec
metadata:
  name: {{ $suffix }}
  namespace: {{ template "windows-ad-setup.namespace" $ }}
  labels: {{ include "windows-ad-setup.labels" $ | nindent 4 }}
credspec:
  ActiveDirectoryConfig:
    GroupManagedServiceAccounts:
      - Name: {{ . }}
        Scope: {{ $.Values.activeDirectory.domain.DNSRoot }}
      - Name: {{ . }}
        Scope: {{ $.Values.activeDirectory.domain.NetBIOSName }}
  DomainJoinConfig:
    Sid: {{ $.Values.activeDirectory.domain.SID }}
    DnsName: {{ $.Values.activeDirectory.domain.DNSRoot }}
    MachineAccountName: {{ . }}
    DnsTreeName: {{ $.Values.activeDirectory.domain.Forest }}
    Guid: {{ $.Values.activeDirectory.domain.ObjectGUID }}
    NetBiosName: {{ $.Values.activeDirectory.domain.NetBIOSName }}
  CmsPlugins:
    - ActiveDirectory
---
apiVersion: windows.k8s.io/v1
kind: GMSACredentialSpec
metadata:
  name: {{ $suffix }}-ccg
  namespace: {{ template "windows-ad-setup.namespace" $ }}
  labels: {{ include "windows-ad-setup.labels" $ | nindent 4 }}
credspec:
  ActiveDirectoryConfig:
    GroupManagedServiceAccounts:
      - Name: {{ . }}
        Scope: {{ $.Values.activeDirectory.domain.DNSRoot }}
      - Name: {{ . }}
        Scope: {{ $.Values.activeDirectory.domain.NetBIOSName }}
    HostAccountConfig:
      PortableCcgVersion: "1"
      PluginGUID: "{e4781092-f116-4b79-b55e-28eb6a224e26}"
      PluginInput: "{{ template "windows-ad-setup.namespace" $ }}:{{ template "windows-ad-setup.name" $ }}-impersonation-account"
  DomainJoinConfig:
    Sid: {{ $.Values.activeDirectory.domain.SID }}
    DnsName: {{ $.Values.activeDirectory.domain.DNSRoot }}
    MachineAccountName: {{ . }}
    DnsTreeName: {{ $.Values.activeDirectory.domain.Forest }}
    Guid: {{ $.Values.activeDirectory.domain.ObjectGUID }}
    NetBiosName: {{ $.Values.activeDirectory.domain.NetBIOSName }}
  CmsPlugins:
    - ActiveDirectory
{{ end }}
