{{- range .Values.activeDirectory.gmsas }}
{{- $suffix := lower . -}}
---
apiVersion: windows.k8s.io/v1
kind: GMSACredentialSpec
metadata:
  name: {{ template "windows-ad-setup.name" $ }}-{{ $suffix }}
  namespace: {{ template "windows-ad-setup.namespace" $ }}
  labels: {{ include "windows-ad-setup.labels" $ | nindent 4 }}
credspec:
  ActiveDirectoryConfig:
    GroupManagedServiceAccounts:
      - Name: {{ . }}
        Scope: {{ $.Values.activeDirectory.domain.DNSRoot }}
      - Name: {{ . }}
        Scope: {{ $.Values.activeDirectory.domain.NetBIOSName }}
  DomainJoinConfig:
    Sid: {{ $.Values.activeDirectory.domain.SID }}
    DnsName: {{ $.Values.activeDirectory.domain.DNSRoot }}
    MachineAccountName: {{ . }}
    DnsTreeName: {{ $.Values.activeDirectory.domain.Forest }}
    Guid: {{ $.Values.activeDirectory.domain.ObjectGUID }}
    NetBiosName: {{ $.Values.activeDirectory.domain.NetBIOSName }}
  CmsPlugins:
    - ActiveDirectory
{{ end }}
