#!/usr/bin/env bash

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -euo pipefail

SCRIPT_PATH=$(realpath "$(dirname "$(readlink -f "$0" 2>/dev/null || realpath "$0")")")
CONFIG_PATH=$(realpath "${1:-${SCRIPT_PATH}/config}")

# Ensure we target the vm-templates root (parent of the "create" directory).
# SCRIPT_PATH is the "create" directory, so its parent is the vm-templates root.
VM_TEMPLATES_ROOT=$(realpath "${SCRIPT_PATH}/..")

# --- Static menu data generated by gomplate from build-vagrant.yaml ---

MENU_ENTRIES=(
  "Microsoft Windows"
)

SUBMENU_ENTRIES=(
  "Windows Server 2025 - Virtual Box - Datacenter Desktop Only"
  "Windows Server 2025 - libvirt - Datacenter Desktop Only"
)

SUBMENU_MESSAGES=(
  "Microsoft Windows Server 2025 Datacenter Desktop Template"
  "Microsoft Windows Server 2025 Datacenter Desktop Template"
)

SUBMENU_PATHS=(
  "builds/windows/server/2025/vagrant"
  "builds/windows/server/2025/vagrant"
)

SUBMENU_ONLY=(
  "virtualbox-iso.windows-server-datacenter-dexp"
  "qemu.windows-server-datacenter-dexp"
)

SUBMENU_PROVIDERS=(
  "virtualbox"
  "libvirt"
)

COMMON_VAR_FILES=(
   "build.pkrvars.hcl" "common.pkrvars.hcl"
)

# --- End static menu data ---


menu_option() {
  local idx="$1"
  local submenu_entry="${SUBMENU_ENTRIES[$idx]}"
  local submenu_message="${SUBMENU_MESSAGES[$idx]}"
  local submenu_path="${SUBMENU_PATHS[$idx]}"
  local submenu_only="${SUBMENU_ONLY[$idx]}"
  local submenu_provider="${SUBMENU_PROVIDERS[$idx]}"
  local var_files="${COMMON_VAR_FILES[0]}" # top-level menu var_files (from YAML)

  # Build directories are children of the vm-templates root.
  INPUT_PATH="$VM_TEMPLATES_ROOT/$submenu_path"
  local message="${submenu_message:-a $submenu_entry Template}"

  # Validate input path exists
  if [[ ! -d "$INPUT_PATH" ]]; then
    echo "ERROR: Build path does not exist: $INPUT_PATH"
    return 1
  fi


  echo ""
  echo "Do you want to provide a custom name prefix for this template?"
  echo "This can be helpful for creating debug templates."
  echo ""
  echo "By default all templates use the format:"
  echo "  [prefix-][OSType]-[Year]-[Edition]-v[Year].[Month]"
  echo "  (e.g. windows-server-2025-datacenter-v25.01)"
  echo ""
  echo -n "Provide custom prefix? (y/n): "
  read -r REPLY

  CUSTOM_NAME=""
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -n "Enter custom name prefix: "
    read -r CUSTOM_NAME
    if [[ -z $CUSTOM_NAME ]]; then
      echo "ERROR: Custom name cannot be empty"
      return 1
    fi
  fi

  echo ""
  echo "=========================================="
  echo "CONFIRM BUILD"
  echo "=========================================="
  echo "Template: $message"
  echo "Path: $INPUT_PATH"
  echo "Target: VirtualBox Vagrant Box"
  if [[ -n "$CUSTOM_NAME" ]]; then
    echo "Prefix: $CUSTOM_NAME"
  fi
  if [[ -n "$submenu_only" ]]; then
    echo "Only: $submenu_only"
  fi
  echo "=========================================="
  echo ""
  echo -n "Continue with build? (y/n): "
  read -r REPLY
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Build cancelled."
    return 0
  fi

  echo ""
  echo "==> Initializing HashiCorp Packer and required plugins..."
  packer init "$INPUT_PATH" || {
    echo "ERROR: Packer initialization failed"
    return 1
  }

  echo ""
  echo "==> Starting build for $message..."

   # Assemble -var-file args
   declare -a varfile_params=()

   # Add any var_files declared in the YAML (look in CONFIG_PATH)
   if [[ -n "$var_files" ]]; then
     for vf in $var_files; do
       if [[ -f "$CONFIG_PATH/$vf" ]]; then
         varfile_params+=("-var-file=$CONFIG_PATH/$vf")
       else
         echo "WARNING: variable file not found: $CONFIG_PATH/$vf"
       fi
     done
   fi

   for val in "${COMMON_VAR_FILES[@]}"; do
     echo "$val"
     if [[ -f "$VM_TEMPLATES_ROOT/config/$val" ]]; then
       varfile_params+=("-var-file=$VM_TEMPLATES_ROOT/config/$val")
     else
       echo "WARNING: common variable file not found: $VM_TEMPLATES_ROOT/config/$val"
     fi
   done

  # Build only argument
  local only_arg=()
  if [[ -n "$submenu_only" ]]; then
    only_arg=(--only "$submenu_only")
  fi

  # Execute packer build
  packer build -force \
    "${only_arg[@]}" \
    "${varfile_params[@]}" \
    -var="custom_template_prefix=${CUSTOM_NAME}" \
    "$INPUT_PATH" || {
    echo "ERROR: Packer build failed"
    return 1
  }

  echo ""
  echo "==> Build completed successfully!"
}

press_enter() {
  cd "$SCRIPT_PATH" || exit 1
  echo ""
  echo -n "Press Enter to continue..."
  read -r
  clear
}

info() {
  clear
  echo ""
  echo "=========================================="
  echo "Rancher Packer Builder for Vagrant"
  echo "=========================================="
  echo ""
  echo "License: BSD-2"
  echo ""
  echo "This tool generates Vagrant boxes for"
  echo "Windows Server using HashiCorp Packer."
  echo ""
  echo "For more information:"
  echo "  GitHub: github.com/rancher/windows"
  echo ""
  echo "=========================================="
  echo ""
  press_enter
}

incorrect_selection() {
  echo ""
  echo "Invalid selection. Please try again."
  echo ""
}

# Main menu loop
while true; do
  clear
  cat << 'EOF'
     ____                       __                    ____                __
    / __ \ ____ _ ____   _____ / /_   ___   _____    / __ \ ____ _ _____ / /__ ___   _____
   / /_/ // __  // __ \ / ___// __ \ / _ \ / ___/   / /_/ // __ // ___// // _// _ \ / ___/
  / _, _// /_/ // / / // /__ / / / //  __// /      / ____// /_/ // /__ / ,<  /  __// /
 /_/ |_| \__,_//_/ /_/ \___//_/ /_/ \___//_/      /_/     \__,_/ \___//_/|_| \___//_/

    ____          _  __     __
   / __ ) __  __ (_)/ /____/ /_____  _____
  / __  |/ / / // // // __  // ___/ / ___/
 / /_/ // /_/ // // // /_/ /(__  ) (__  )
/_____/ \__,_//_//_/ \__,_//____/ /____/

EOF
  echo "  Select a HashiCorp Packer build to generate Vagrant boxes:"
  echo ""

  idx=0
  echo "  Microsoft Windows:"
  echo ""
  printf "    %2d  -  Windows Server 2025 - Virtual Box - Datacenter Desktop Only\n" "$((idx+1))"
  idx=$((idx+1))
  printf "    %2d  -  Windows Server 2025 - libvirt - Datacenter Desktop Only\n" "$((idx+1))"
  idx=$((idx+1))
  echo ""

  echo "  Other:"
  echo ""
  echo "    I   -  Information"
  echo "    Q   -  Quit"
  echo ""
  echo -n "  Selection: "
  read -r selection

  if [[ "$selection" =~ ^[0-9]+$ ]] && (( selection > 0 && selection <= ${#SUBMENU_ENTRIES[@]} )); then
    clear
    menu_option $((selection-1))
    press_enter
  elif [[ "$selection" =~ ^[Ii]$ ]]; then
    info
  elif [[ "$selection" =~ ^[Qq]$ ]]; then
    clear
    echo "Goodbye!"
    exit 0
  else
    incorrect_selection
    sleep 2
  fi
done
