menu:
  - entry: "Microsoft Windows"
    build:
      var_files:
        - "vsphere.pkrvars.hcl"
        - "build.pkrvars.hcl"
        - "common.pkrvars.hcl"
    submenu:
      - entry: "Windows Server 2022 - All"
        message: "all Windows Server 2022 Templates"
        build:
          path: "builds/windows/server/2022/"
      - entry: "Windows Server 2022 - Standard Only (Core And Desktop)"
        message: "Microsoft Windows Server 2022 Standard Templates"
        build:
          path: "builds/windows/server/2022/"
          only:
            - vsphere-iso.windows-server-standard-dexp
            - vsphere-iso.windows-server-standard-core
      - entry: "Windows Server 2022 - Standard Core Only"
        message: "Microsoft Windows Server 2022 Standard Core Template"
        build:
          path: "builds/windows/server/2022/"
          only:
            - vsphere-iso.windows-server-standard-core
      - entry: "Windows Server 2022 - Standard Desktop Only"
        message: "Microsoft Windows Server 2022 Standard Desktop Template"
        build:
          path: "builds/windows/server/2022/"
          only:
            - vsphere-iso.windows-server-standard-dexp
      - entry: "Windows Server 2022 - Datacenter Only (Core And Desktop)"
        message: "Microsoft Windows Server 2022 Datacenter Templates"
        build:
          path: "builds/windows/server/2022/"
          only:
            - vsphere-iso.windows-server-datacenter-dexp
            - vsphere-iso.windows-server-datacenter-core
      - entry: "Windows Server 2022 - Datacenter Core Only"
        message: "Microsoft Windows Server 2022 Datacenter Templates"
        build:
          path: "builds/windows/server/2022/"
          only:
            - vsphere-iso.windows-server-datacenter-core
      - entry: "Windows Server 2022 - Datacenter Desktop Only"
        message: "Microsoft Windows Server 2022 Datacenter Templates"
        build:
          path: "builds/windows/server/2022/"
          only:
            - vsphere-iso.windows-server-datacenter-dexp
            - vsphere-iso.windows-server-datacenter-core
      - entry: "Windows Server 2019 - All"
        message: "all Windows Server 2019 Templates"
        build:
          path: "builds/windows/server/2019/"
      - entry: "Windows Server 2019 - Standard Only (Core And Desktop)"
        message: "Microsoft Windows Server 2019 Standard Templates"
        build:
          path: "builds/windows/server/2019/"
          only:
            - vsphere-iso.windows-server-standard-dexp
            - vsphere-iso.windows-server-standard-core
      - entry: "Windows Server 2019 - Standard Core Only"
        message: "Microsoft Windows Server 2019 Standard Core Template"
        build:
          path: "builds/windows/server/2019/"
          only:
            - vsphere-iso.windows-server-standard-core
      - entry: "Windows Server 2019 - Standard Desktop Only"
        message: "Microsoft Windows Server 2019 Standard Desktop Template"
        build:
          path: "builds/windows/server/2019/"
          only:
            - vsphere-iso.windows-server-standard-dexp
      - entry: "Windows Server 2019 - Datacenter Only (Core And Desktop)"
        message: "Microsoft Windows Server 2019 Datacenter Templates"
        build:
          path: "builds/windows/server/2019/"
          only:
            - vsphere-iso.windows-server-datacenter-dexp
            - vsphere-iso.windows-server-datacenter-core
      - entry: "Windows Server 2019 - Datacenter Core Only"
        message: "Microsoft Windows Server 2019 Datacenter Core Template"
        build:
          path: "builds/windows/server/2019/"
          only:
            - vsphere-iso.windows-server-datacenter-core
      - entry: "Windows Server 2019 - Datacenter Desktop Only"
        message: "Microsoft Windows Server 2019 Datacenter Desktop Template"
        build:
          path: "builds/windows/server/2019/"
          only:
            - vsphere-iso.windows-server-datacenter-dexp